about/urls.py
from django.conf.urls import url 
from . import views

appname = 'about'
urlpatterns = [
	url(r'^$', views.index, name='basic'),
	url(r'^geekwars$', views.usGeeks, name='usGeeks')
] 

cart/urls.py
from django.conf.urls import url 
from . import views

appname = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

contact/urls.py
from django.conf.urls import url 
from . import views

appname = 'contact'
urlpatterns = [
	url(r'^$', views.index, name='contact'),
]

events/urls.py
from django.conf.urls import url
from . import views

appname = 'events'

urlpatterns = [
	url(r'^$', views.index, name='event'),
	url(r'^calendar$', views.calendar, name='calendar')
]

home/urls.py
from django.conf.urls import url 
from . import views

app_name='home'
urlpatterns = [
	url(r'^$', views.post_list, name='index'),
]

mill_geek2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
 	url(r'^', include('home.urls', namespace='home')),
    #url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
 	#url(r'^log_reg/', include('log_reg.urls', namespace='log_reg')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^castus/', include('contact.urls', namespace='contact')),
    url(r'^about/', include('about.urls', namespace='about')),
 	url(r'^cart/', include('cart.urls', namespace='cart')),  
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payments')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
    url(r'^shop/', include('shop.urls', namespace='shop')),  
 ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

appname = 'shop'

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

events/models.py
# # -*- coding: utf-8 -*-
# from __future__ import unicode_literals
# from django.contrib import admin
# from django.contrib.auth.models import User
# from django.db import models

# from oauth2client.contrib.django_util.models import CredentialsField

# class CredentialsModel(models.Model):
# 	id = models.ForeignKey(User, primary_key=True)
# 	credential = CredentialsField()

# class CredentialsAdmin(admin.ModelAdmin):
# 	pass

events/views.py
from __future__ import unicode_literals

from django.shortcuts import render


def index(request):
	return render(request, 'events/events.html')

def calendar(request):
	return render(request, 'events/calendar.html')

events/templates/events/calendar.html
<html>
<head>
	<meta charset="UTF-8">
	<title>Mill Geek Comics</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/calendar.css' %}">
</head>
<body>
	<nav>
		<a href="{% url 'home:index' %}">Home</a>
		<a href="{% url 'about:basic' %}">About Us</a>
		<a href="{% url 'shop:product_list' %}">Shop</a>
		<a href="{% url 'contact:contact' %}">Contact Us</a>
		<a href="{% url 'events:event' %}">Events</a>
	</nav>
	<div id="wrapper" >
		<iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=millgeekcomics%40gmail.com&amp;color=%23B1365F&amp;ctz=America%2FLos_Angeles" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
	</div>
</body>
</html>

events/templates/events/events.html
<html>
<head>
	<meta charset="UTF-8">
	<title>Events</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/events.css' %}">
</head>
<body>
	<h1>Magic Events</h1>
	<nav>
		<a href="{% url 'home:index' %}">Home</a>
		<a href="{% url 'about:basic' %}">About Us</a>
		<a href="{% url 'shop:product_list' %}">Shop</a>
		<a href="{% url 'cart:cart_detail' %}">Cart</a>
		<a href="{% url 'events:calendar' %}">Calendar</a>
	</nav>
	<article>
		<section id="Thur">
			<h2>Thursdays</h2>
			<h4>MTG - Commander Casual</h4>
			<p id="time">6pm - 10pm</p>
			<p id="context">Bring your Commander deck and come play with Us!</p>
			<p id="context">These are free events</p>
			<a href="https://magic.wizards.com/en/content/commander-format">View Rules</a>
		</section>
		<section id="Fri">
			<h2>Fridays</h2>
			<h4>MTG - FNM: Booster Draft</h4>
			<p id="time">6pm - 11pm</p>
			<p id="context">Draft starts a <b>7pm SHARP</b> but please get here early to get signed up and settled. These can get <b>VERY</b> full and sometimes we will hit full capacity</p><br>
			<p>Booster draft tournament of the latest sets with prozes!</p>
			<a href="https://magic.wizards.com/en/game-info/gameplay/formats/booster-draft">View Rules</a>
		</section>
		<section id="Sat">
			<h2>Saturdays</h2>
			<h4>MTG - Free Play</h4>
			<p id="time">12:30pm - 6pm</p>
			<p id="context">Bring a deck and test it against others! This is free and just for fun.</p>
		</section>
	</article>
	
</body>
</html>