about/urls.py
from django.conf.urls import url 
from . import views

appname = 'about'
urlpatterns = [
	url(r'^$', views.index, name='basic'),
	url(r'^geekwars$', views.usGeeks, name='usGeeks')
] 

cart/urls.py
from django.conf.urls import url 
from . import views

appname = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

contact/urls.py
from django.conf.urls import url 
from . import views

appname = 'contact'
urlpatterns = [
	url(r'^$', views.index, name='contact'),
]

events/urls.py
from django.conf.urls import url
from . import views

appname = 'events'

urlpatterns = [
	url(r'^$', views.index, name='event'),
	url(r'^calendar$', views.calendar, name='calendar')
]

home/urls.py
from django.conf.urls import url 
from . import views

app_name='home'
urlpatterns = [
	url(r'^$', views.post_list, name='index'),
]

mill_geek2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
 	url(r'^', include('home.urls', namespace='home')),
    #url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
 	#url(r'^log_reg/', include('log_reg.urls', namespace='log_reg')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^castus/', include('contact.urls', namespace='contact')),
    url(r'^about/', include('about.urls', namespace='about')),
 	url(r'^cart/', include('cart.urls', namespace='cart')),  
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payments')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
    url(r'^shop/', include('shop.urls', namespace='shop')),  
 ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

appname = 'shop'

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

about/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
def usGeeks(request):
	return render(request, 'about/about.html')

def index(request):
	return render(request, 'about/classicUs.html')

about/templates/about/about.html
<html>
<head>
	<meta charset="UTF-8">
	<title>Mill Geek Comics</title>
	{% load static %}
	<link rel="stylesheet" href="../static/css/usGeeks.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://use.fontawesome.com/4d0cb8d848.js"></script>
	
	
</head>
<body>
	<div id="navBox">
			<a id="returnButton" href="{% url 'about:basic' %}"><button>Back</button></a>
			<a id="homeButton" href="{% url 'home:index' %}"><button>Home</button></a>
		
	</div>
	<div class="fade"></div>
	<section class="geekWars">
		<div class="crawl">
			<div class="title">
				<h1>Mill Geek Comics</h1>
			</div>
			<p>Mill Geek Comics is a quickly growing comic book, Magic the Gathering and gaming shop serving Mill Creek, Bothell and the surrounding areas. We welcome collectors and players of all ages and experience levels. If you have an interest in any of the items we sell of games we play at the shop, we invite you to come pay us a visit. Nurturing new collectors and players is one of the points we pride our shop on the most.</p><br>
			<p>Not only is our collection of comics and cards for sale, but we also buy collections you may not want anymore. If you or anyone you know have old comics or cards that you are looking to sell, please bring them by! Russ, owner of Mill Geek Comics, will tell you what they are worth. He is always looking for exciting new items and will either trade, pay or provide store credit for things he is interested in.</p><br>
			<p>Russ and everyone that works here at the shop have been geeks their entire life! We celebrate all that is geek and are always eager to meet others that share our interests. Mill Geek Comics is a haven for geeks! Please come by the shop and see for yourself what an inviting place it is.</p><br>
			<p>Please get in touch with us if you have any questions about our events, buying or selling items. We always welcome your calls, emails, and shop visits. Don’t forget to ask about getting your very own subscription box with us!</p>
		</div>
	</section>
</body>
</html>

about/templates/about/classicUs.html
<html>
<head>
	<meta charset="UTF-8">
	<title>Mill Geek Comics</title>
	{% load static %}
	<link rel="stylesheet" href="../static/css/basic.css">
</head>
<body>
	<div class='header-content'>
		<h1>Mill Geek Comics</h1>

		<h4>Feeling like 'spacing' out? <a href="{% url 'about:usGeeks' %}">Click Here!!</a></h4>
	</div>
	<div class="topNav">
		<a href="{% url 'home:index' %}">Home</a>
		<a href="{% url 'contact:contact' %}">Contact Us</a>
		<a href="{% url 'events:event' %}">Events</a>
		<a href="{% url 'events:calendar' %}">Calendar</a>
		<a href="{% url 'shop:product_list' %}">Shop</a>
	</div>
	
	
	<div class="main-content">
		<p>Mill Geek Comics is a quickly growing comic book, Magic the Gathering and gaming shop serving Mill Creek, Bothell and the surrounding areas. We welcome collectors and players of all ages and experience levels. If you have an interest in any of the items we sell of games we play at the shop, we invite you to come pay us a visit. Nurturing new collectors and players is one of the points we pride our shop on the most.</p><br>

		<p>Not only is our collection of comics and cards for sale, but we also buy collections you may not want anymore. If you or anyone you know have old comics or cards that you are looking to sell, please bring them by! Russ, owner of Mill Geek Comics, will tell you what they are worth. He is always looking for exciting new items and will either trade, pay or provide store credit for things he is interested in.</p><br>

		<p>Russ and everyone that works here at the shop have been geeks their entire life! We celebrate all that is geek and are always eager to meet others that share our interests. Mill Geek Comics is a haven for geeks! Please come by the shop and see for yourself what an inviting place it is.</p><br>

		<p>Please get in touch with us if you have any questions about our events, buying or selling items. We always welcome your calls, emails, and shop visits. Don’t forget to ask about getting your very own subscription box with us!</p>
	</div>
	
</body>
</html>